### PR TITLE
Change Share() to Singleton

### PR DESCRIPTION
**Pull request by ErenPhayte**
Fixing issue addressed here https://github.com/univerze/laravel-jira/issues/17

### CODE REVIEW

**Review by johannesschobel — CHANGES_REQUESTED** [review]
This is a duplicate of #16 ?!

**Comment by ErenPhayte** [comment]
Yes it is apparently! Much needed requirement.
Close this pull request and merge the other?

**Comment by johannesschobel** [comment]
It is questionable, if this repository is still active ... The last commit was about 2 years ago..
Maybe @univerze can give further information?

**Comment by rolandbecsi** [comment]
Hi guys, indeed this repo is inactive now, please feel free to fork and improve, I'm sure a lot has changed since in both Laravel and Jira api! All the best.

**Comment by johannesschobel** [comment]
hey @univerze ..
wow, thank you for your very quick response.. I am very glad to see that you merged the PR, even though you declared the repository as "inactive".. I will provide a PR to clearly indicate that this repository is closed..

Thank you very much and have a nice weekend!

**Comment by rolandbecsi** [comment]
hi @johannesschobel thanks for your pull request, I have merged it. Happy coding!

**Pull request merged**
